_BASE_: "Base-MapInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  CONDINST:
    MASK_HEAD:
      DISABLE_REL_COORDS: True
      MAPPING_RATIO: 1.5
      GRID_NUM: [2, ]
OUTPUT_DIR: "output/2x-P3-1.5xmap-mapinst_MS_R_50_1x"
