_BASE_: "Base-CondInst.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
#  CONDINST:
#    MASK_HEAD:
#      DISABLE_REL_COORDS: True
OUTPUT_DIR: "output/condinst_ori_MS_R_50_1x"
